config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :biddings do
    resources :quotations, shallow: true
  end
  resources :tasks
  resources :bank_account_types
  resources :banks
  resources :providers
  resources :menu_items
  resources :phone_types
  resources :cities
  resources :states
  resources :document_types
  resources :categories do
    post :products, on: :member
  end
  resources :responsabilities, only: [:create, :destroy]
  resources :entry_descriptions, only: [:create]
  resources :products do
    get :lots, on: :member
    post :lots, on: :member
  end
  resources :users do
    get :remove_role, on: :member
    post :add_role, on: :member
  end
  resources :units do
    resources :lots, shallow: true do
      get :out, on: :collection
    end
    resources :entries, shallow: true do
      get :in, on: :collection
      get :out, on: :collection
    end
    resources :contracts, shallow: true
  end
  resources :orders do
    get :in, on: :member
    get :pay, on: :member
  end
  devise_for :users, path: 'auth'
      root to: 'home#index'
  # devise_scope :user do
  #   authenticated :user do
  #     root to: 'home#index'
  #   end

  #   unauthenticated do
  #     root to: 'devise/sessions#new'
  #   end
  # end
  get 'home/index'
  post 'utils/zipcode'
end

app/views/shared/_aside.html.erb
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MENU PRINCIPAL</li>
      <% @menu.each do |mi| %>
        <% if can? mi.permission.to_sym, eval_with_rescue(mi.permission_check) %>
          <% unless mi.menu_items.exists? %>
            <li <%= "class=active" if controller_name == mi.active_test %>>
              <%= link_to eval(mi.link) do %>
                <i class="fa fa-<%= mi.icon %>"></i> <span><%= mi.name %></span>
              <% end %>
            </li>
          <% else %>
            <li class="treeview <%= 'active' if mi.menu_items.pluck(:active_test).include? controller_name %>">
              <a href="#">
                <i class="fa fa-<%= mi.icon %>"></i><span><%= mi.name %></span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <% mi.menu_items.each do |c| %>
                  <!-- mostrar filhos do menu apenas se tiver permissão -->
                  <% if can? c.permission.to_sym, eval_with_rescue(c.permission_check) %>
                    <% unless c.menu_items.exists? %>
                      <li <%= "class=active" if controller_name == c.active_test %>>
                        <%= link_to eval(c.link), target: c.target do %>
                            <i class="fa fa-<%= c.icon %>"></i><%= c.name %>
                        <% end %>
                      </li>
                    <% else %>
                      <li class="treeview <%= 'active' if mi.menu_items.pluck(:active_test).include? controller_name %>">
                        <a href="#">
                          <i class="fa fa-<%= c.icon %>"></i><span><%= c.name %></span>
                          <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                          </span>
                        </a>
                        <ul class="treeview-menu">
                          <% c.menu_items.each do |cc| %>
                            <li <%= "class=active" if controller_name == cc.active_test %>>
                              <%= link_to eval(cc.link), target: cc.target do %>
                                <i class="fa fa-<%= cc.icon %>"></i><%= cc.name %>
                              <% end %>
                            </li>
                          <% end %>
                        </ul>
                      </li>
                    <% end %>
                  <% end %>
                <% end %>
              </ul>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="float-right hidden-xs">
    <%= image_tag 'chaleville_logo.png', style: 'width: 120px; margin-top: -10px;' %>
  </div>
  <strong>Perfecta Criações</strong>
  <%= link_to "&copy;".html_safe, new_user_session_path, class: 'text-danger' %>
  2018-<%= Date.today.year %>
</footer>

app/views/shared/_header.html.erb
<nav class="main-header navbar navbar-expand navbar-dark navbar-danger">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
  </ul>
  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
        <i class="fa fa-user"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <%= image_tag "chaleville-flor.png", class: "img-size-50 mr-3 img-circle" %>
            <!--
            <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            -->            
            <div class="media-body">
              <h3 class="dropdown-item-title">
                <%= current_user&.email %>
              </h3>
              <p class="text-sm">
                Membro desde <%=l(current_user.created_at, format: :monthyear) if current_user %>
              </p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 
                <%= distance_of_time_in_words(Time.zone.now, current_user&.current_sign_in_at) %>
              </p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <div class="row">
          <div class="col">
            <%= link_to destroy_user_session_path, class: 'dropdown-item dropdown-footer', method: "delete" do %>
              <i class="fa fa-sign-out-alt"></i> Sair
            <% end %>
          </div>
        </div>
      </div>
    </li>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<aside class="main-sidebar elevation-4 sidebar-light-danger">
  <!-- Brand Logo -->
  <%= link_to root_path, class: 'brand-link navbar-danger' do %>
    <span class="logo-lg">
      <%= image_tag 'chaleville-flor.png', class: 'brand-image', width: '50px' %>
    </span>
    <span class="brand-text text-white">
      <strong>SGC</strong>
    </span>
  <% end %>
  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <% @menu.each do |mi| %>
          <% if can? mi.permission.to_sym, eval_with_rescue(mi.permission_check) %>
            <% unless mi.menu_items.exists? %>
              <li class='nav-item'>
                <%= link_to eval(mi.link), class: "nav-link #{"active" if controller_name == mi.active_test}" do %>
                  <i class="nav-icon fas fa-<%= mi.icon %>"></i>
                  <p><%= mi.name %></p>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item has-treeview <%= 'menu-open' if mi.menu_items.pluck(:active_test).include? controller_name %>">
                <a href="#" class="nav-link <%= 'active' if mi.menu_items.pluck(:active_test).include? controller_name %>">
                  <i class="nav-icon fas fa-<%= mi.icon %>"></i>
                  <p>
                    <%= mi.name %>
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <% mi.menu_items.each do |c| %>
                    <!-- mostrar filhos do menu apenas se tiver permissão -->
                    <% if can? c.permission.to_sym, eval_with_rescue(c.permission_check) %>
                      <% unless c.menu_items.exists? %>
                        <li class='nav-item'>
                          <%= link_to eval(c.link), target: c.target, class: "nav-link #{'active' if controller_name == c.active_test}" do %>
                            <i class="nav-icon fas fa-<%= c.icon %>"></i>
                            <p><%= c.name %></p>
                          <% end %>
                        </li>
                      <% else %>
                        <li class="nav-item has-treeview <%= 'menu-open' if mi.menu_items.pluck(:active_test).include? controller_name %>">
                          <a href="#" class="nav-link <%= 'active' if mi.menu_items.pluck(:active_test).include? controller_name %>">
                            <i class="nav-icon fas fa-<%= c.icon %>"></i>
                            <p>
                              <%= c.name %>
                              <i class="right fas fa-angle-left"></i>
                            </p>
                          </a>
                          <ul class="nav nav-treeview">
                            <% c.menu_items.each do |cc| %>
                              <li class='nav-item'>
                                <%= link_to eval(cc.link), target: cc.target, class: "nav-link #{'active' if controller_name == cc.active_test}" do %>
                                  <i class="nav-icon fas fa-<%= cc.icon %>"></i>
                                  <p>
                                    <%= cc.name %>
                                  </p>
                                <% end %>
                              </li>
                            <% end %>
                          </ul>
                        </li>
                      <% end %>
                    <% end %>
                  <% end %>
                </ul>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
  </aside>

app/views/shared/_title.html.erb
<div class="content-header">
  <% unless controller_name == "registrations" or controller_name == "sessions" or controller_name == "home" %>
    <%- value = "helpers.titles.#{action_name}" -%>
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">
            <%=t value %>
            <% if action_name == "index" %>
              <%=t 'of' %> <%= Kernel.const_get(controller_name.singularize.camelize).model_name.human.downcase.pluralize %>
            <% else %>
              <%= Kernel.const_get(controller_name.singularize.camelize).model_name.human.downcase %>
            <% end -%>
            <small class='text-red'>
              <%= @app_name %>
            </small>
          </h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class='breadcrumb-item'>
              <%= link_to root_url do %>
                <i class="fa fa-home"></i> Início
              <% end %>
            </li>
            <% if @unit %>
              <% @unit.path.each do |un| %>
                <li class='breadcrumb-item active'>
                  <%= link_to un.name, unit_entries_path(un) %>
                </li>
              <% end %>
            <% end %>
            <!-- <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li> -->
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  <% end %>
</div>

app/views/shared/_tree.html.erb
<div class="card card-outline card-danger">
  <div class="card-header with-border">
    <h3 class="card-title">
      Unidades
      <% if can? :manage, Unit %>
        <%= link_to new_unit_path, class: "btn btn-danger btn-xs" do %>
          <i class='fa fa-plus'></i>
        <% end %>
      <% end %>
    </h3>
  </div>
  <div class="card-body">
    <div id="tree"></div>
  </div>
</div>