config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :biddings do
    resources :quotations, shallow: true
  end
  resources :tasks
  resources :bank_account_types
  resources :banks
  resources :providers
  resources :menu_items
  resources :phone_types
  resources :cities
  resources :states
  resources :document_types
  resources :categories do
    post :products, on: :member
  end
  resources :responsabilities, only: [:create, :destroy]
  resources :entry_descriptions, only: [:create]
  resources :products do
    get :lots, on: :member
    post :lots, on: :member
  end
  resources :users do
    get :remove_role, on: :member
    post :add_role, on: :member
  end
  resources :units do
    resources :lots, shallow: true do
      get :out, on: :collection
    end
    resources :entries, shallow: true do
      get :in, on: :collection
      get :out, on: :collection
    end
    resources :contracts, shallow: true
  end
  resources :orders do
    get :in, on: :member
    get :pay, on: :member
  end
  devise_for :users, path: 'auth'
      root to: 'home#index'
  # devise_scope :user do
  #   authenticated :user do
  #     root to: 'home#index'
  #   end

  #   unauthenticated do
  #     root to: 'devise/sessions#new'
  #   end
  # end
  get 'home/index'
  post 'utils/zipcode'
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  has_paper_trail

  belongs_to :provider
  belongs_to :user
  belongs_to :bidding, optional: true

  has_many :prices, dependent: :destroy

  has_many :products, through: :prices
  has_many :tasks, through: :prices

  accepts_nested_attributes_for :prices, allow_destroy: true

  monetize :shipping_cents
  monetize :prices_value_cents

  def products_prices
    self.prices.where.not(product_id: nil)
  end

  def tasks_prices
    self.prices.where.not(task_id: nil)
  end

  def list_products
    self.products.pluck(:name).join(", ")
  end

  def list_tasks
    self.tasks.pluck(:name).join(", ")
  end

  def user_name
    user&.the_name
  end

  def prices_value_cents
    self.prices.sum(:value_cents)
  end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  load_and_authorize_resource :bidding
  load_and_authorize_resource :quotation, through: :bidding, shallow: true

  # GET /quotations
  def index
    @q = Quotation.ransack(params[:q])
    @quotations = @q.result(distinct: true)
    @quotations = @quotations.page(params[:page])
  end

  # GET /quotations/1
  def show
  end

  # GET /quotations/new
  def new
    @quotation.register = Time.zone.now
    @bidding.bidding_items.each do |bi|
      @quotation.prices.build(
        product: bi.product,
        task: bi.task
      )
    end
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  def create
    @quotation = @bidding.quotations.new(quotation_params)
    @quotation.user = current_user

    if @quotation.save
      redirect_to @quotation, notice: 'Quotation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /quotations/1
  def update
    if @quotation.update(quotation_params)
      redirect_to @quotation, notice: 'Quotation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /quotations/1
  def destroy
    @quotation.destroy
    redirect_to quotations_url, notice: 'Quotation was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def quotation_params
      params.require(:quotation).permit(
        :register, :provider_id, :shipping, :term, :bidding_id,
        prices_attributes: [
          :id, :_destroy, :product_id, :task_id, :value
        ]
      )
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.erb
<%= simple_form_for([@bidding, @quotation]) do |f| %>
  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">
        Dados do <%=t Quotation.model_name.human %>
      </h3>
    </div>
    <div class="card-body no-padding">
      <%= render 'biddings/show', bidding: @quotation.bidding %>
    </div>
  </div>

  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">
        Registro de Preços
      </h3>
    </div>
    <div class="card-body">
      <div class="row">
        <%= f.association :provider, wrapper_html: { class: 'col-md-3' }, input_html: { class: 'select2' } %>
        <%= f.input :register, html5: true, wrapper_html: { class: 'col-md-3' } %>
        <%= f.input :shipping, wrapper_html: { class: 'col-md-3' }, input_html: { class: 'currency' } %>
        <%= f.input :term, wrapper_html: { class: 'col-md-3' } %>
      </div>
    </div>
  </div>

  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">Produtos</h3>
    </div>
    <div class="card-body">
      <div id="quotation_products">
        <%= f.simple_fields_for :prices do |v| %>
          <% unless v.object.product_id.nil? %>
            <%= render 'price_fields', f: v, kind: 'product' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">Serviços</h3>
    </div>
    <div class="card-body">
      <div id="quotation_tasks">
        <%= f.simple_fields_for :prices do |v| %>
          <% unless v.object.task_id.nil? %>
            <%= render 'price_fields', f: v, kind: 'task' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card card-outline card-danger">
    <div class="card-footer">
      <%= link_to t('.cancel', default: t("helpers.links.cancel")), bidding_quotations_path(@quotation.bidding), class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/quotations/_price_fields.html.erb
<div class="row price nested-fields">
  <div class="col-lg-3 col-xs-3">
    <%= f.association kind.to_sym, disabled: true %>
    <%= f.input "#{kind}_id", as: :hidden %>
  </div>
  <div class="col-lg-2 col-xs-2">
    <%= f.input :value, input_html: { class: 'currency' } %>
  </div>
</div>

app/views/quotations/edit.html.erb
<%= render 'form', box_class: 'danger' %>

app/views/quotations/index.html.erb
<div class="card card-outline card-danger">
  <div class="card-header with-border">
    <h3 class="card-title">Cotação</h3>
    <% if can? :edit, @bidding %> <!--verificando se o usuario esta logado-->
      <%= link_to new_bidding_path, class: "btn btn-danger btn-xs", data: { toggle: 'tooltip', placement: 'top', title: 'Cadastrar' } do %>
        <i class="fa fa-plus"></i> Cadastrar
      <% end %>
    <% end %>
    <%= link_to 'Listagem', biddings_path, class: "btn btn-default btn-xs" %>
  </div>
  <div class="card-body no-padding">
    <%= render 'biddings/show', bidding: @bidding %>
  </div>
</div>

<%= render 'shared/index', list: @quotations, box_class: 'danger',
  additional_columns: ['list_products'],
  nested_resource: true,
  parent_resource: 'bidding',
  sort_fields: ['id', 'register', 'shipping_cents', 'provider_id'],
  excluded_columns: ['user_id'],
  additional_columns: ['user_name', 'prices_value_cents'],
  search_fields: [
    { field: 'provider_name_cont', label: 'Fornecedor' }
  ]
%>

app/views/quotations/new.html.erb
<%= render 'form', box_class: 'danger' %>

app/views/quotations/show.html.erb
<div class="card card-outline card-danger">
  <div class="card-header with-border">
    <h3 class="card-title">Cotação</h3>
    <% if can? :edit, @quotation %> <!--verificando se o usuario esta logado-->
      <%= link_to edit_quotation_path(@quotation), class: "btn btn-warning btn-xs", data: { toggle: 'tooltip', placement: 'top', title: 'Editar' } do %>
        <i class="fa fa-pencil"></i> Editar
      <% end %>
    <% end %>
    <%= link_to 'Listagem', bidding_quotations_path(@quotation.bidding), class: "btn btn-default btn-xs" %>
  </div>
  <div class="card-body no-padding">
    <%= render 'biddings/show', bidding: @quotation.bidding %>
  </div>
</div>

<div class="card card-outline card-danger">
  <div class="card-header with-border">
    <h3 class="card-title">Dados Registrados</h3>
  </div>
  <div class="card-body no-padding">
    <table class="table table-bordered table-striped no-padding styletable">
      <thead>
        <th><%= Provider.model_name.human %></th>
        <th><%= Quotation.human_attribute_name(:shipping) %></th>
        <th><%= Quotation.human_attribute_name(:term) %></th>
        <th><%= Quotation.human_attribute_name(:register) %></th>
      </thead>
      <tbody>
        <tr>
          <td><%= @quotation.provider.name %></td>
          <td><%= number_to_currency @quotation.shipping %></td>
          <td><%= @quotation.term %> dias</td>
          <td><%=l @quotation.register if @quotation.register %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<% if @quotation.products_prices.any? %>
  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">
        Cotação dos <%= Product.model_name.human.pluralize %>
      </h3>
    </div>
    <div class="card-body no-padding">
      <table class="table table-bordered table-striped no-padding styletable">
        <thead>
          <tr>
            <th width='15%'>
              <%= Price.human_attribute_name(:product) %>
            </th>
            <th>
              <%= Price.human_attribute_name(:value) %>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @quotation.products_prices.each do |pr| %>
            <tr>
              <td>
                <%= pr.product.name %>
              </td>
              <td>
                <%= number_to_currency pr.value %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<% if @quotation.tasks_prices.any? %>
  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">
        Cotação dos <%= Task.model_name.human.pluralize %>
      </h3>
    </div>
    <div class="card-body no-padding">
      <table class="table table-bordered table-striped no-padding styletable">
        <thead>
          <tr>
            <th width='15%'>
              <%= Price.human_attribute_name(:task) %>
            </th>
            <th>
              <%= Price.human_attribute_name(:value) %>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @quotation.tasks_prices.each do |pr| %>
            <tr>
              <td>
                <%= pr.task.name %>
              </td>
              <td>
                <%= number_to_currency pr.value %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>