config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :biddings do
    resources :quotations, shallow: true
  end
  resources :tasks
  resources :bank_account_types
  resources :banks
  resources :providers
  resources :menu_items
  resources :phone_types
  resources :cities
  resources :states
  resources :document_types
  resources :categories do
    post :products, on: :member
  end
  resources :responsabilities, only: [:create, :destroy]
  resources :entry_descriptions, only: [:create]
  resources :products do
    get :lots, on: :member
    post :lots, on: :member
  end
  resources :users do
    get :remove_role, on: :member
    post :add_role, on: :member
  end
  resources :units do
    resources :lots, shallow: true do
      get :out, on: :collection
    end
    resources :entries, shallow: true do
      get :in, on: :collection
      get :out, on: :collection
    end
    resources :contracts, shallow: true
  end
  resources :orders do
    get :in, on: :member
    get :pay, on: :member
  end
  devise_for :users, path: 'auth'
      root to: 'home#index'
  # devise_scope :user do
  #   authenticated :user do
  #     root to: 'home#index'
  #   end

  #   unauthenticated do
  #     root to: 'devise/sessions#new'
  #   end
  # end
  get 'home/index'
  post 'utils/zipcode'
end

app/models/bidding.rb
class Bidding < ApplicationRecord
  has_paper_trail

  belongs_to :user

  has_many :bidding_items, dependent: :destroy

  has_many :products, through: :bidding_items
  has_many :tasks, through: :bidding_items

  accepts_nested_attributes_for :bidding_items, allow_destroy: true

  has_many :quotations

  def products_bidding_items
    self.bidding_items.where.not(product_id: nil)
  end

  def tasks_bidding_items
    self.bidding_items.where.not(task_id: nil)
  end

  def list_products
    self.products.pluck(:name).join(", ")
  end

  def list_tasks
    self.tasks.pluck(:name).join(", ")
  end

  def user_name
    user.the_name
  end
end

app/controllers/biddings_controller.rb
class BiddingsController < ApplicationController
  load_and_authorize_resource

  # GET /biddings
  def index
  end

  # GET /biddings/1
  def show
  end

  # GET /biddings/new
  def new
  end

  # GET /biddings/1/edit
  def edit
  end

  # POST /biddings
  def create
    @bidding = Bidding.new(bidding_params)
    @bidding.user = current_user

    if @bidding.save
      redirect_to @bidding, notice: 'Bidding was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /biddings/1
  def update
    if @bidding.update(bidding_params)
      redirect_to @bidding, notice: 'Bidding was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /biddings/1
  def destroy
    @bidding.destroy
    redirect_to biddings_url, notice: 'Bidding was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def bidding_params
      params.require(:bidding).permit(:name, :description, :user_id,
        bidding_items_attributes: [
          :id, :_destroy, :product_id, :task_id
        ]
      )
    end
end

app/helpers/biddings_helper.rb
module BiddingsHelper
end

app/views/biddings/_bidding_item_fields.html.erb
<div class="row bidding_item nested-fields">
  <div class="col-md-3">
    <%= f.association kind.to_sym, label: I18n.t("activerecord.models.#{kind}"), input_html: { class: 'select2' } %>
  </div>
  <div class="col-md-1">
    <%= link_to_remove_association f, class: 'remove_bidding_item_fields' do %>
      <div class="btn btn-danger top-25">
        <i class="fa fa-fw fa-trash-alt"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/biddings/_form.html.erb
<%= simple_form_for(object) do |f| %>
  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">
        Dados da <%=t Bidding.model_name.human %>
      </h3>
    </div>
    <div class="card-body">
      <div class="row">
        <%= f.input :name, wrapper_html: { class: 'col-md-4' } %>
        <%= f.input :description, wrapper_html: { class: 'col-md-8' } %>
      </div>
    </div>
  </div>

  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">Produtos</h3>
    </div>
    <div class="card-body">
      <div id="bidding_products">
        <%= f.simple_fields_for :bidding_items do |v| %>
          <% unless v.object.product_id.nil? %>
            <%= render 'bidding_item_fields', f: v, kind: 'product' %>
          <% end %>
        <% end %>

        <div class="control-group">
          <div class="controls">
            <%= link_to_add_association f, :bidding_items, id: 'add_price',
              render_options: { locals: { kind: 'product' }} do %>
              <div class="btn btn-success">
                <i class="fa fa-fw fa-plus"></i> Adicionar Produto
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">Serviços</h3>
    </div>
    <div class="card-body">
      <div id="bidding_tasks">
        <%= f.simple_fields_for :bidding_items do |v| %>
          <% unless v.object.task_id.nil? %>
            <%= render 'bidding_item_fields', f: v, kind: 'task' %>
          <% end %>
        <% end %>

        <div class="control-group">
          <div class="controls">
            <%= link_to_add_association f, :bidding_items, id: 'add_price',
              render_options: { locals: { kind: 'task' }} do %>
              <div class="btn btn-success">
                <i class="fa fa-fw fa-plus"></i> Adicionar Serviço
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card card-outline card-danger">
    <div class="card-footer">
      <%= link_to t('.cancel', default: t("helpers.links.cancel")), biddings_path, class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/biddings/_show.html.erb
<table class="table table-bordered table-striped no-padding styletable">
  <thead>
    <th><%= Bidding.human_attribute_name(:name) %></th>
    <th><%= Bidding.human_attribute_name(:description) %></th>
    <th><%= Product.model_name.human.pluralize %></th>
    <th><%= Task.model_name.human.pluralize %></th>
  </thead>
  <tbody>
    <tr>
      <td><%= bidding.name %></td>
      <td><%= bidding.description %></td>
      <td><%= bidding.list_products %></td>
      <td><%= bidding.list_tasks %></td>
    </tr>
  </tbody>
</table>

app/views/biddings/edit.html.erb
<%= render 'form', object: @bidding, box_class: 'danger' %>

app/views/biddings/index.html.erb
<%= render 'shared/index', list: @biddings, box_class: 'danger',
  table_no_padding: true,
  excluded_columns: ['user_id'],
  additional_columns: ['user_name']
%>

app/views/biddings/new.html.erb
<%= render 'form', object: @bidding, box_class: 'danger' %>

app/views/biddings/show.html.erb
<div class="card card-outline card-danger">
  <div class="card-header with-border">
    <h3 class="card-title">Cotação</h3>
    <% if can? :edit, @bidding %> <!--verificando se o usuario esta logado-->
      <%= link_to new_bidding_path, class: "btn btn-danger btn-xs", data: { toggle: 'tooltip', placement: 'top', title: 'Cadastrar' } do %>
        <i class="fa fa-plus"></i> Cadastrar
      <% end %>
    <% end %>
    <% if can? :edit, @bidding %> <!--verificando se o usuario esta logado-->
      <%= link_to edit_bidding_path(@bidding), class: "btn btn-warning btn-xs", data: { toggle: 'tooltip', placement: 'top', title: 'Editar' } do %>
        <i class="fa fa-pencil"></i> Editar
      <% end %>
    <% end %>
    <%= link_to 'Listagem', biddings_path, class: "btn btn-default btn-xs" %>
  </div>
  <div class="card-body no-padding">
    <%= render 'biddings/show', bidding: @bidding %>
  </div>
</div>

<div class="card card-outline card-danger">
  <div class="card-header with-border">
    <h3 class="card-title">
      <%= Quotation.model_name.human.pluralize %>
      <% if can? :new, Quotation %> <!--verificando se o usuario esta logado-->
        <%= link_to new_bidding_quotation_path(@bidding), class: "btn btn-danger btn-xs", data: { toggle: 'tooltip', placement: 'top', title: 'Cadastrar' } do %>
          <i class="fa fa-plus"></i> Cadastrar
        <% end %>
      <% end %>
    </h3>
  </div>
  <div class="card-body no-padding">
    <% if @bidding.quotations.any? %>
      <%= render 'shared/list', list: @bidding.quotations %>
    <% end %>
  </div>
</div>