config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :biddings do
    resources :quotations, shallow: true
  end
  resources :tasks
  resources :bank_account_types
  resources :banks
  resources :providers
  resources :menu_items
  resources :phone_types
  resources :cities
  resources :states
  resources :document_types
  resources :categories do
    post :products, on: :member
  end
  resources :responsabilities, only: [:create, :destroy]
  resources :entry_descriptions, only: [:create]
  resources :products do
    get :lots, on: :member
    post :lots, on: :member
  end
  resources :users do
    get :remove_role, on: :member
    post :add_role, on: :member
  end
  resources :units do
    resources :lots, shallow: true do
      get :out, on: :collection
    end
    resources :entries, shallow: true do
      get :in, on: :collection
      get :out, on: :collection
    end
    resources :contracts, shallow: true
  end
  resources :orders do
    get :in, on: :member
    get :pay, on: :member
  end
  devise_for :users, path: 'auth'
      root to: 'home#index'
  # devise_scope :user do
  #   authenticated :user do
  #     root to: 'home#index'
  #   end

  #   unauthenticated do
  #     root to: 'devise/sessions#new'
  #   end
  # end
  get 'home/index'
  post 'utils/zipcode'
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_paper_trail

  resourcify
  acts_as_tree order: "name"
  has_ancestry

  has_many :entries
  has_many :lots
  has_many :orders
  has_many :contracts

  has_many :components, through: :lots
  has_many :products, -> { distinct.reorder('products.name asc') }, through: :components

  validates :name, :parent_id, presence: true

  def fullpath
    self.path.pluck(:name).join(' > ')
  end

  def parent_name
    parent&.name
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  load_and_authorize_resource

  # GET /units
  def index
    @q = Unit.ransack(params[:q])
    @units = @q.result(distinct: true)
    @units = @units.page(params[:page])
  end

  # GET /units/1
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
    @unit.parent_id = params[:parent_id] if params[:parent_id]
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to @unit, notice: t("helpers.links.save_success_f", model: Unit.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /units/1
  def update
    if @unit.update(unit_params)
      redirect_to @unit, notice: t("helpers.links.save_success_f", model: Unit.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /units/1
  def destroy
    @unit.destroy
    redirect_to units_url, notice: t("helpers.links.destroyed_f", model: Unit.model_name.human)
  end

  private
    # Only allow a trusted parameter "white list" through.
    def unit_params
      params.require(:unit).permit(:name, :description, :parent_id, :warehouse)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= simple_form_for(@unit) do |f| %>
  <div class="card card-outline card-danger">
    <div class="card-header with-border">
      <h3 class="card-title">
        Dados da <%= Unit.model_name.human %>
      </h3>
    </div>
    <div class="card-body">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.association :parent, label_method: :fullpath %>
      <%= f.input :warehouse %>
    </div>
    <div class="card-footer">
      <%= link_to t('.cancel', default: t("helpers.links.cancel")), units_path, class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/units/edit.html.erb
<%= render 'form' %>

app/views/units/index.html.erb
<div class="card card-outline card-danger">
  <div class="card-header with-border">
    <h3 class="card-title">
      Pesquisar <%=t Unit.model_name.human %>
    </h3>
  </div>
  <div class="card-body">
    <%= search_form_for @q do |f| %>
      <div class="row">
        <%= f.input :name_cont, label: 'Nome', required: false, wrapper_html: { class: 'col-md-3' } %>
        <%= f.input :ancestry_cont, label: 'Pai', required: false, collection: Unit.order(:name),
          wrapper_html: { class: 'col-md-3' }, input_html: { class: 'select2' }
        %>
        <div class="col-md-12">
          <%= f.submit 'Pesquisar', class: 'btn btn-danger' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="card card-outline card-danger">
  <div class="card-header with-border">
    <h3 class="card-title">
      <%= Unit.model_name.human.pluralize %>
      <% if can? :create, Unit %>
        <%= link_to new_unit_url, class: "btn btn-danger btn-xs" do %>
          Cadastrar <i class='fa fa-plus'></i>
        <% end %>
      <% end %>
    </h3>
    <div class="card-tools pull-right">
      <%= paginate @units %>
    </div>
  </div>
  <table class="table table-striped styletable">
    <thead>
      <tr>
        <th>#</th>
        <th><%= Unit.human_attribute_name(:name) %></th>
        <th><%= Unit.human_attribute_name(:path) %></th>
        <th><%= Unit.human_attribute_name(:parent) %></th>
        <th><%= Unit.human_attribute_name(:warehouse) %></th>
        <th class='text-center'><%=t '.actions', default: t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @units.each do |unit| %>
      <tr>
        <td>
          <%= link_to unit.id, unit, class: 'text-danger' %>
        </td>
        <td>
          <%= unit.name %>
        </td>
        <td>
          <%= unit.fullpath %>
        </td>
        <td>
          <%= unit.parent&.name %>
        </td>
        <td>
          <%=t unit.warehouse %>
        </td>
        <td style='white-space: nowrap' class='text-center'>
          <%= render 'shared/action_links', object: unit %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/units/new.html.erb
<%= render 'form' %>

app/views/units/show.html.erb
<%= render 'shared/show',
  object: @unit,
  show_columns: ['name', 'description', 'fullpath', 'parent_name', 'warehouse'],
  box_class: 'danger'
%>